### ISSUE TITLE
Cloud Error Mac M1  

### ISSUE THREAD

**Issue by codeTCbin25** [armory3d/armortools#1668]
**ArmorPaint version:**
Bought Mac Version 1.0

**OS/device including version:**
Mac OS 14 . Macbook Pro M1.  8 GB 

**Issue description:**
I can't connect to the Cloud in Armour Paint 1.0 . 
Error Check internet connection.
internet is on. Also i disabled the Firewall.

**Steps to reproduce:**
Try on Mac. Version 1.0 . Try to load the cloud assets.

**Comment by luboslenco** [comment]
Thanks for report. Will investigate cloud issues here.

(For people having issues on Linux, see https://github.com/armory3d/armortools/issues/1231#issuecomment-1105675465)

**Comment by empoweredindie** [comment]
Hi,

I am having the same exact problem. Should I open a new thread? Is there a solution? Thanks.

**Comment by ZMVT** [comment]
I don't know if it will help, I bought it through itch.io. The problem disappeared when I launched armorpaint via itch.io app.

**Comment by Fullyottermatic** [comment]
Having the same problem on Ubuntu 24.04.1, nothing seems to load in the cloud tab in the asset browser. I get these errors in my console when it tries to load:
`Resolving armorpaint.fra1.digitaloceanspaces.com (armorpaint.fra1.digitaloceanspaces.com)... failed: Name or service not known.
wget: unable to resolve host address ‘armorpaint.fra1.digitaloceanspaces.com’
`

The comment mentioned above on issue #1231 doesn't seem to apply anymore, as the described folder structure doesn't exist in the version I built from source today.

**Comment by luboslenco** [comment]
It should be resolved - any luck connecting to the cloud with the latest builds?

**Comment by Crimson-Fox** [comment]
Built last night and tested cloud to look at materials, issue is persisting
`Error: Check internet connection to access the cloud`

**Comment by Glockenbeat** [comment]
Same here

**Comment by CuriosMind** [comment]
For those who still have this bug. In my case the solution was to install wget via `sudo pacman -S wget` on my Arch Linux distribution. In my case wget was simply not installed causing it to fail when trying to download the files.

**Comment by luboslenco** [comment]
I have added an error message when wget is missing to make it clear https://github.com/armory3d/armortools/commit/6c3d37d17e404a1c5d8311addea4489d3d54e9fa. Thanks for mentioning that. Will eventually get rid of the wget dependency.

I have also been testing on macos and it should work fine now, thanks for reports.
